=== Timoner/Repository_Marc/actividad23/actividad23.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="factura">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="direccion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="calle" type="xs:string" />
                                        <xs:element name="provincia" type="xs:string" />
                                        <xs:element name="codi_postal" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="n_CIF" type="xs:string" />
                            <xs:element name="telefono" type="xs:string" />
                            <xs:element name="fax" type="xs:string" />
                            <xs:element name="fecha">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia" type="xs:string" />
                                        <xs:element name="mes" type="xs:string" />
                                        <xs:element name="aÃ±o" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="pedido">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:integer" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="forma_de_pago" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="datos_cliente">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="numero_cliente" type="xs:string" />
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="direccion" type="xs:string" />
                            <xs:element name="poblacion" type="xs:string" />
                            <xs:element name="codigo_postal" type="xs:string" />
                            <xs:element name="provincia" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datos_factura">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="producto">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="n_ref" type="xs:string" />
                                        <xs:element name="descripcion" type="xs:string" />
                                        <xs:element name="cantidad" type="xs:string" />
                                        <xs:element name="precio" type="xs:string" />
                                        <xs:element name="iva" type="xs:string" />
                                        <xs:element name="importe" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="productos" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="n_ref" type="xs:string" />
                                        <xs:element name="descripcion" minOccurs="0"
                                            type="xs:string" />
                                        <xs:element name="cantidad" type="xs:string" />
                                        <xs:element name="precio" type="xs:string" />
                                        <xs:element name="iva" type="xs:string" />
                                        <xs:element name="importe" minOccurs="0" type="xs:string" />
                                        <xs:element name="descripcion" minOccurs="0"
                                            type="xs:string" />
                                        <xs:element name="Importe" minOccurs="0" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="base_imponible" type="xs:string" />
                            <xs:element name="cant_iva" type="xs:string" />
                            <xs:element name="cuota_iva" type="xs:string" />
                            <xs:element name="total_factura" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Timoner/Repository_Marc/actividad23/actividad23.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="actividad15.xsl" type="text/xsl"?>   
<Factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="actividad23.xsd">
    <factura id="999">

        <nombre>Equipos Digitals S.L.</nombre>
        <direccion>
            <calle>AV.Valladolid</calle>
            <provincia>Madrid</provincia>
            <codi_postal>28015</codi_postal>
        </direccion>
        <n_CIF>Q-9876543</n_CIF>
        <telefono>917776688</telefono>
        <fax>917776699</fax>
        <fecha>
            <dia>12</dia>
            <mes>1</mes>
            <año>2005</año>
        </fecha>
        <pedido id="731"></pedido>
        <forma_de_pago>Efectivo</forma_de_pago>
    </factura>

    <datos_cliente>

        <numero_cliente>879</numero_cliente>
        <nombre>Darío Bueno Gutiérrez</nombre>
        <direccion> AV.Oporto n7 4d</direccion> 
        <poblacion>Madrid</poblacion>
        <codigo_postal>28043</codigo_postal>
        <provincia>Madrid</provincia>

    </datos_cliente>

    <datos_factura>

        <productos>

            <n_ref>MII93000F</n_ref>
            <descripcion>Micro pentium IV 3000MHZ FB800</descripcion>
            <cantidad>1</cantidad>
            <precio>230 euro</precio>
            <iva>16%</iva>
            <importe>266.80 euro</importe>
        </productos>

        <productos>
            <n_ref> MB8QDIp4 </n_ref>
            <descripcion>Placa base QDI P4</descripcion>
            <cantidad>1</cantidad>
            <precio>180 euro</precio>
            <iva>16%</iva>
            <importe>208.80 euro</importe>
        </productos>

        <productos>
            <n_ref>MEDD512M32</n_ref>
            <descripcion>DIMM DDR 512MB 3200</descripcion>
            <cantidad>2</cantidad>
            <precio>40 eurp</precio>
            <iva>16%</iva>
            <importe>92.80 euro</importe>
        </productos>

        <productos>
            <n_ref>HD250GSA7</n_ref>
            <descripcion>DISCO DURO 250GB S-ATA 7200</descripcion>
            <cantidad>4</cantidad>
            <precio>120 euro</precio>
            <iva>16%</iva>
            <Importe>556.80 euro</Importe>
        </productos>

        <base_imponible>970.00 euro</base_imponible>
        <cant_iva>16%</cant_iva>
        <cuota_iva>155.20 euro</cuota_iva>
        <total_factura>1125.20 euro</total_factura>
        
    </datos_factura>

</Factura>
