<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE matricula  
[
<!ELEMENT matricula (personal, pago)>
<!ELEMENT personal (dni,nombre,titulacion,curso_academico,domicilios)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT titulacion (#PCDATA)>
<!ELEMENT curso_academico (#PCDATA)>
<!ELEMENT domicilios (domicilio+)>
<!ELEMENT domicilio (#PCDATA)>
<!ATTLIST domicilio tipo (familiar | habitual)  PCDATA "familiar" #REQUIRED>
]> 
<matricula>
    <personal>
        <dni>99223366M</dni>
        <nombre>Juan Pardo Martín</nombre>
        <titulacion>Ingeniería Informática</titulacion>
        <curso_academico>1997/1998</curso_academico>
                    <!-- domicilio almenos 1+ -->
        <domicilios><!-- Tipo es Obligatorio i solo puede  valore: “familiar” o “habitua   --> 
            <domicilio tipo="familiar">
                <nombre>C/ Principal nº1</nombre>
            </domicilio>
            <domicilio tipo="habitual">
             <nombre>C/ Secundaria nº2</nombre>
            </domicilio>
        </domicilios>
    </personal>
    <pago>
        <tipo_matricula>Matrícula Ordinaria</tipo_matricula>
    </pago>
</matricula>    