=== Timoner/Repository_Marc/actividad25/actividad25.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="factura">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="empresa" type="xs:string" />
                            <xs:element name="direccion" type="xs:string" />
                            <xs:element name="id_CIF" type="xs:string" />
                            <xs:element name="telefono" type="xs:string" />
                            <xs:element name="fax" type="xs:string" />
                            <xs:element name="fecha" type="xs:string" />
                            <xs:element name="pedido" type="xs:string" />
                            <xs:element name="forma_pago" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datos_cliente">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="n_cliente" type="xs:string" />
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="direccion" type="xs:string" />
                            <xs:element name="poblacion" type="xs:string" />
                            <xs:element name="codigo_postal" type="xs:string" />
                            <xs:element name="provincia" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datos_factura">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="datos" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="REF" type="xs:string" />
                                        <xs:element name="descripcion" type="xs:string" />
                                        <xs:element name="cant" type="xs:string" />
                                        <xs:element name="precio" type="xs:string" />
                                        <xs:element name="iva" type="xs:string" />
                                        <xs:element name="importe" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="cod" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="TOTAL_FACTURA_PRECIO">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="factura" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="name" use="required" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="total_factura" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Timoner/Repository_Marc/actividad25/actividad25.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="actividad25.xsd"?>
<?xml-stylesheet href="actividad25.xsl" type="text/xsl"?>
<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="actividad25.xsd" id="nº 999">
    <factura>   
        <empresa>Equipos Digitales S.L.</empresa>
        <direccion>Av. Valladolid, Madrid 28015</direccion>
        <id_CIF>Q-9876543</id_CIF>
        <telefono>91 777 66 88</telefono>
        <fax>91 777 66 99</fax>
        <fecha>12-01-2005</fecha>
        <pedido>nº 731</pedido>
        <forma_pago>Efectivo</forma_pago>
    </factura>
    <datos_cliente>
        <n_cliente>879</n_cliente>
        <nombre>Dario Bueno Gutiérrez</nombre>
        <direccion>Av. Oporto nº7 4ºd</direccion>
        <poblacion>Madrid</poblacion>
        <codigo_postal>28043</codigo_postal>
        <provincia>Madrid</provincia>
    </datos_cliente>

    <datos_factura>
        <datos cod="MII93000F8">
                <REF>MII93000F/8</REF>
                <descripcion>Micro pentium IV 3000MHZ FB800</descripcion>
                <cant>1</cant>
                <precio>230 eur.</precio>
                <iva>16,0</iva>
                <importe>266,80 eur.</importe>
        </datos>
        <datos cod="MB8QDIP4">
                    <REF>MB8QDIP4</REF>
                    <descripcion>Placa base QDI P4</descripcion>
                    <cant>1</cant>
                    <precio>180 eur.</precio>
                    <iva>16,0</iva>
                    <importe>208,80 eur.</importe>
        </datos>
        <datos cod="MEDD512M32">
                    <REF>MEDD512M32</REF>
                    <descripcion>DIMM DDR 512MB 3200</descripcion>
                    <cant>2</cant>
                    <precio>40 eur.</precio>
                    <iva>16,0</iva>
                    <importe>92,80 eur.</importe>
        </datos>
        <datos cod="HD250GSA7">
                 <REF>HD250GSA7</REF>
                 <descripcion>Disco duro 250GB S-ATA 7200</descripcion>
                    <cant>4</cant>
                    <precio>120 eur.</precio>
                    <iva>16,0</iva>
                    <importe>556,80 eur.</importe>
        </datos>
    </datos_factura>
   
    <TOTAL_FACTURA_PRECIO>
        <factura name="base imponible">970,00 eur.</factura>
        <factura name="IVA">16,0</factura>
        <factura name="Cuota I.V.A.">155,20 eur.</factura>
        <total_factura>1125,20 eur</total_factura>
    </TOTAL_FACTURA_PRECIO>
</factura>
